FROM python:3
ADD main.py /
ADD create_project.py /
ADD edit_project.py /
ADD projects.txt /
ADD remove_project.py /
ADD sign_in.py /
ADD sign_up.py /
ADD signup.txt /
ADD user_projects.py /
CMD [ "python", "./main.py" ]
